# Generated by Django 6.0.4 on 2026-04-16 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColocationAnnonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=100)),
                ('quartier', models.CharField(blank=True, max_length=100)),
                ('budget_mensuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('infos_logement', models.TextField(blank=True)),
                ('nombre_colocataires', models.PositiveSmallIntegerField(default=1)),
                ('profil_recherche', models.CharField(blank=True, max_length=200)),
                ('conditions_vie', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
