# Generated by Django 6.0.4 on 2026-04-17 20:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colocation', '0002_favori'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colocationannonce',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='colocationannonce',
            name='climatisation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='colocationannonce',
            name='cuisine_equipee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='colocationannonce',
            name='disponible_depuis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colocationannonce',
            name='durée_minimum',
            field=models.PositiveSmallIntegerField(default=6, help_text='Durée minimum de location en mois'),
        ),
        migrations.AddField(
            model_name='colocationannonce',
            name='garage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='colocationannonce',
            name='jardin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='colocationannonce',
            name='meuble',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='colocationannonce',
            name='nombre_chambres',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='colocationannonce',
            name='nombre_salles_bain',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='colocationannonce',
            name='surface',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='colocationannonce',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='colocationannonce',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='colocationannonce',
            name='budget_mensuel',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='colocationannonce',
            name='nombre_colocataires',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='colocationannonce',
            name='profil_recherche',
            field=models.CharField(blank=True, choices=[('etudiant', 'Étudiant'), ('professionnel', 'Professionnel'), ('couple', 'Couple'), ('famille', 'Famille'), ('autre', 'Autre')], default='autre', max_length=20),
        ),
        migrations.CreateModel(
            name='PhotoColocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='colocations/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='colocation.colocationannonce')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
