# Generated by Django 6.0.4 on 2026-09-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0002_alter_message_options_remove_message_destinataire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Texte'), ('image', 'Image'), ('file', 'Fichier'), ('audio', 'Audio'), ('system', 'Système')], default='text', max_length=10),
        ),
    ]
