# Generated by Django 6.0.7 on 2026-10-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0006_appelsession_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationconversation',
            name='masquee',
            field=models.BooleanField(default=False),
        ),
    ]
