# Generated by Django 6.0.4 on 2026-04-17 20:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='logement',
            name='climatisation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logement',
            name='cuisine_equipee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logement',
            name='disponible_depuis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logement',
            name='etage',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logement',
            name='garage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logement',
            name='jardin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logement',
            name='meuble',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logement',
            name='nombre_chambres',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='logement',
            name='nombre_pieces',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='logement',
            name='nombre_salles_bain',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='logement',
            name='piscine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logement',
            name='quartier',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='logement',
            name='surface',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='logement',
            name='type_logement',
            field=models.CharField(choices=[('appartement', 'Appartement'), ('maison', 'Maison'), ('studio', 'Studio'), ('villa', 'Villa'), ('chambre', 'Chambre')], default='appartement', max_length=20),
        ),
        migrations.AddField(
            model_name='logement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='logement',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='logement',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='PhotoLogement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logements/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='logement.logement')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
