# Generated by Django 6.0.4 on 2026-05-13 00:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0002_alter_logement_options_logement_climatisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='account_type',
            field=models.CharField(choices=[('hotel', 'Hôtel'), ('residence', 'Résidence'), ('individu', 'Individu')], default='individu', max_length=20),
        ),
        migrations.AddField(
            model_name='logement',
            name='ascenseur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logement',
            name='buanderie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logement',
            name='capacite',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='logement',
            name='caution_mois',
            field=models.PositiveSmallIntegerField(blank=True, default=2, null=True),
        ),
        migrations.AddField(
            model_name='logement',
            name='coffre_fort',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logement',
            name='conditions_speciales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logement',
            name='duree_min_bail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logement',
            name='frais_agence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='logement',
            name='frais_nettoyage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='logement',
            name='gardien',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logement',
            name='min_sejour',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='logement',
            name='minibar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logement',
            name='nombre_lits',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='logement',
            name='prix_par_mois',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='logement',
            name='prix_par_nuit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='logement',
            name='reception_24h',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logement',
            name='restaurant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logement',
            name='securite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logement',
            name='television',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logement',
            name='type_charge',
            field=models.CharField(blank=True, choices=[('charges_comprises', 'Charges comprises'), ('charges_non_comprises', 'Charges non comprises')], max_length=25, null=True),
        ),
    ]
