# Generated by Django 6.0.4 on 2026-05-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0003_logement_account_type_logement_ascenseur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photologement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='logements/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='photologement',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
