# Generated by Django 6.0.4 on 2026-05-14 01:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0004_alter_photologement_image_alter_photologement_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logement',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix global (pour individu) - Voir prix_par_nuit ou prix_par_mois pour les professionnels', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
