# Generated by Django 6.0.4 on 2026-05-14 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0005_alter_logement_prix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_nom', models.CharField(max_length=200)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_telephone', models.CharField(max_length=20)),
                ('date_arrivee', models.DateField()),
                ('date_depart', models.DateField()),
                ('nombre_personnes', models.PositiveSmallIntegerField(default=1)),
                ('nombre_chambres', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('remarques', models.TextField(blank=True)),
                ('prix_par_nuit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_nuits', models.PositiveSmallIntegerField()),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frais_service', models.DecimalField(decimal_places=2, default=0, help_text='Frais de service/commission', max_digits=10)),
                ('frais_nettoyage_reservation', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('montant_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('pending', '⏳ En attente de paiement'), ('confirmed', '✅ Confirmée'), ('cancelled', '❌ Annulée'), ('completed', '✓ Complétée')], default='pending', max_length=20)),
                ('paye', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='logement.logement')),
            ],
            options={
                'verbose_name_plural': 'Réservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('methode', models.CharField(choices=[('stripe', 'Carte bancaire (Stripe)'), ('virement', 'Virement bancaire'), ('cash', 'Paiement sur place')], default='stripe', max_length=20)),
                ('statut', models.CharField(choices=[('pending', '⏳ En attente'), ('completed', '✅ Complété'), ('failed', '❌ Échoué'), ('refunded', '↩️ Remboursé')], default='pending', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='ID de la transaction Stripe', max_length=255)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='logement.reservation')),
            ],
            options={
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisponibiliteCalendrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('statut', models.CharField(choices=[('disponible', '✅ Disponible'), ('occupe', '❌ Occupé'), ('bloquer', '🚫 Bloqué')], default='disponible', max_length=20)),
                ('prix_special', models.DecimalField(blank=True, decimal_places=2, help_text='Prix spécial pour cette date (si vide, utilise prix standard)', max_digits=10, null=True)),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='logement.logement')),
            ],
            options={
                'verbose_name_plural': 'Disponibilités Calendrier',
                'ordering': ['date'],
                'unique_together': {('logement', 'date')},
            },
        ),
    ]
