# Generated by Django 6.0.4 on 2026-05-19 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0006_reservation_paiement_disponibilitecalendrier'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLogement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, help_text='Accepte les formats: MP4, WebM, Ogg (max 500 MB)', null=True, upload_to='logements/videos/%Y/%m/')),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('duree_secondes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='logement.logement')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
