# Generated by Django 6.0.4 on 2026-05-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0007_videologement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='methode',
            field=models.CharField(choices=[('mouv', '🟠 MOUV (Étoile)'), ('orange', '🟠 Orange Money'), ('wave', '🔵 Wave'), ('stripe', '💳 Carte bancaire (Stripe)'), ('virement', '🏦 Virement bancaire'), ('cash', '💵 Paiement sur place')], default='stripe', max_length=20),
        ),
    ]
