# Generated by Django 6.0.4 on 2026-06-23 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0008_alter_paiement_methode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriLogement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris_users', to='logement.logement')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris_logements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Favoris Logements',
                'ordering': ['-created_at'],
                'unique_together': {('utilisateur', 'logement')},
            },
        ),
    ]
