# Generated by Django 6.0.7 on 2026-09-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0013_logement_search_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logement',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='logement',
            name='eau',
        ),
        migrations.RemoveField(
            model_name='logement',
            name='electricite',
        ),
        migrations.AddField(
            model_name='etablissement',
            name='commune',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='eau',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='electricite',
            field=models.BooleanField(default=False),
        ),
    ]
