# Generated by Django 6.0.7 on 2026-09-14 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0014_professional_inventory_calendar'),
        ('logement', '0014_remove_logement_commune_remove_logement_eau_and_more'),
    ]

    operations = [
    ]
