# Generated by Django 6.0.4 on 2026-09-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0015_merge_20260914_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='cinetpay_payment_token',
            field=models.CharField(
                blank=True,
                help_text="payment_token renvoyé par CinetPay à l'initialisation",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name='paiement',
            name='transaction_id',
            field=models.CharField(
                blank=True,
                help_text='Identifiant unique envoyé à CinetPay pour cette transaction',
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='methode',
            field=models.CharField(
                choices=[
                    ('mobile_money', '📱 Mobile Money (Orange, MOUV, Moov, Wave)'),
                    ('stripe', '💳 Carte bancaire (Stripe)'),
                    ('virement', '🏦 Virement bancaire'),
                    ('cash', '💵 Paiement sur place'),
                    ('mouv', '🟠 MOUV (ancien)'),
                    ('orange', '🟠 Orange Money (ancien)'),
                    ('wave', '🔵 Wave (ancien)'),
                ],
                default='stripe',
                max_length=20,
            ),
        ),
    ]