# Generated by Django 6.0.7 on 2026-10-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0017_unite_logement_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='methode',
            field=models.CharField(choices=[('mobile_money', '📱 Mobile Money (Orange, MOUV, Moov, Wave)'), ('mouv', '🟠 MOUV (ancien)'), ('orange', '🟠 Orange Money (ancien)'), ('wave', '🔵 Wave (ancien)'), ('stripe', '💳 Carte bancaire (Stripe)'), ('virement', '🏦 Virement bancaire'), ('cash', '💵 Paiement sur place')], default='stripe', max_length=20),
        ),
    ]
