# Generated by Django 6.0.7 on 2026-10-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0018_alter_paiement_methode'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='cinetpay_notify_token',
            field=models.CharField(blank=True, help_text='notify_token renvoyé par CinetPay (vérifie les notifications)', max_length=255),
        ),
    ]
