# Generated by Django 6.0.4 on 2026-04-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adresse_complete',
            field=models.TextField(blank=True, help_text='Adresse complète'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_back',
            field=models.ImageField(blank=True, help_text="Photo verso de la pièce d'identité", null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_front',
            field=models.ImageField(blank=True, help_text="Photo recto de la pièce d'identité", null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='selfie',
            field=models.ImageField(blank=True, help_text="Selfie avec pièce d'identité", null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telephone',
            field=models.CharField(blank=True, help_text='Numéro de téléphone', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False, help_text='Profil vérifié'),
        ),
    ]
