# Generated by Django 6.0.4 on 2026-04-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_adresse_complete_profile_id_back_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='adresse_complete',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='animaux',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fumeur',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id_back',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id_front',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='selfie',
        ),
        migrations.AddField(
            model_name='profile',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='quartier',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
