# Generated by Django 6.0.4 on 2026-04-17 21:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_adresse_complete_remove_profile_age_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AddField(
            model_name='profile',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='derniere_connexion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='numero_piece_identite',
            field=models.CharField(default='', help_text="Numéro de la pièce d'identité", max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='type_piece_identite',
            field=models.CharField(choices=[('cni', "Carte Nationale d'Identité"), ('passport', 'Passeport'), ('permis', 'Permis de conduire'), ('carte_sejour', 'Carte de séjour')], default='cni', help_text="Type de pièce d'identité", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo_profil',
            field=models.ImageField(help_text='Photo de profil obligatoire', upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('locataire', 'Locataire'), ('colocataire', 'Colocataire'), ('proprietaire', 'Propriétaire')], default='locataire', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ville',
            field=models.CharField(max_length=100),
        ),
    ]
