# Generated by Django 6.0.4 on 2026-04-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_options_profile_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='numero_piece_identite',
            field=models.CharField(blank=True, help_text="Numéro de la pièce d'identité", max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type_piece_identite',
            field=models.CharField(blank=True, choices=[('cni', "Carte Nationale d'Identité"), ('passport', 'Passeport'), ('permis', 'Permis de conduire'), ('carte_sejour', 'Carte de séjour'), ('carte_etudiant', "Carte d'étudiant")], help_text="Type de pièce d'identité", max_length=20),
        ),
    ]
