# Generated by Django 6.0.4 on 2026-04-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_numero_piece_identite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo_profil',
            field=models.ImageField(blank=True, help_text='Photo de profil', null=True, upload_to='profiles/'),
        ),
    ]
