# Generated by Django 6.0.4 on 2026-05-09 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_photo_profil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(choices=[('pending', '⏳ En attente de vérification'), ('verified', '✅ Vérifié'), ('rejected', '❌ Rejeté'), ('flagged', '⚠️ Signalé')], default='pending', help_text="Statut de vérification de l'inscription", max_length=20),
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Inscription créée'), ('document_uploaded', 'Document téléchargé'), ('document_verified', 'Document approuvé'), ('document_rejected', 'Document rejeté'), ('profile_flagged', 'Profil signalé'), ('profile_verified', 'Profil vérifié'), ('profile_banned', 'Profil banni')], max_length=30)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='accounts.profile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_front', "Pièce d'identité - Avant"), ('id_back', "Pièce d'identité - Arrière"), ('selfie', "Selfie avec pièce d'identité"), ('proof_address', 'Preuve de résidence')], max_length=20)),
                ('document_file', models.FileField(upload_to='verification_docs/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', '⏳ En attente'), ('verified', '✅ Approuvé'), ('rejected', '❌ Rejeté'), ('flagged', '⚠️ À revoir')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text="Notes pour l'admin sur la vérification")),
                ('rejection_reason', models.CharField(blank=True, help_text='Raison du rejet', max_length=255)),
                ('file_hash', models.CharField(blank=True, help_text='SHA256 du fichier pour anti-fraude', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.profile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'unique_together': {('profile', 'document_type')},
            },
        ),
    ]
