# Generated by Django 6.0.4 on 2026-05-12 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_verification_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('individu', 'Individu'), ('residence', 'Gestionnaire de Résidence'), ('hotel', "Gestionnaire d'Hôtel")], default='individu', help_text='Type de compte utilisateur', max_length=20),
        ),
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment_type', models.CharField(choices=[('residence', 'Résidence'), ('hotel', 'Hôtel')], help_text="Type d'établissement", max_length=20)),
                ('establishment_name', models.CharField(help_text="Nom officiel de l'établissement", max_length=200)),
                ('siret_or_rccm', models.CharField(help_text="SIRET (France) ou RCCM (Côte d'Ivoire)", max_length=50, unique=True)),
                ('legal_representative', models.CharField(help_text="Représentant légal de l'établissement", max_length=150)),
                ('legal_phone', models.CharField(help_text='Téléphone de contact légal', max_length=20)),
                ('establishment_address', models.CharField(max_length=255)),
                ('establishment_city', models.CharField(max_length=100)),
                ('establishment_postal_code', models.CharField(blank=True, max_length=10)),
                ('establishment_country', models.CharField(default="Côte d'Ivoire", max_length=100)),
                ('number_of_rooms', models.PositiveIntegerField(help_text='Nombre de chambres/unités')),
                ('number_of_floors', models.PositiveIntegerField(blank=True, help_text="Nombre d'étages", null=True)),
                ('website', models.URLField(blank=True, help_text="Site web de l'établissement")),
                ('wifi', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('restaurant', models.BooleanField(default=False)),
                ('reception_24h', models.BooleanField(default=False, help_text='Réception 24h/24')),
                ('air_conditioning', models.BooleanField(default=False)),
                ('laundry_service', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('conference_room', models.BooleanField(default=False)),
                ('legal_document', models.FileField(help_text='Document légal de constitution', upload_to='professional_docs/%Y/%m/')),
                ('establishment_photo', models.ImageField(help_text="Photo de façade de l'établissement", upload_to='professional_photos/%Y/%m/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to='accounts.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
