# Generated by Django 6.0.4 on 2026-05-18 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_account_type_professionalprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_listing', 'Nouvelle annonce'), ('subscription', 'Nouvel abonné'), ('message', 'Nouveau message'), ('reservation', 'Nouvelle réservation'), ('system', 'Notification système')], default='system', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('related_listing_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_subscription_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Utilisateur qui a déclenché la notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_created', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(help_text='Utilisateur qui reçoit la notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='accounts_no_recipie_8b48cc_idx'), models.Index(fields=['recipient', '-created_at'], name='accounts_no_recipie_799191_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notify_on_new_listing', models.BooleanField(default=True, help_text='Notifier quand cette personne publie une annonce')),
                ('creator', models.ForeignKey(help_text="Utilisateur dont on s'abonne", on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL)),
                ('subscriber', models.ForeignKey(help_text="Utilisateur qui s'abonne", on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-subscribed_at'],
                'indexes': [models.Index(fields=['subscriber', 'is_active'], name='accounts_su_subscri_7ed37d_idx'), models.Index(fields=['creator', 'is_active'], name='accounts_su_creator_0d68a9_idx')],
                'unique_together': {('subscriber', 'creator')},
            },
        ),
    ]
