# Generated by Django 6.0.4 on 2026-06-27 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_colocataire_to_touriste'),
        ('accounts', '0009_notification_subscription'),
    ]

    operations = [
    ]
