# Generated by Django 6.0.4 on 2026-07-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_merge_20260627_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo_couverture',
            field=models.ImageField(blank=True, help_text='Photo de couverture', null=True, upload_to='profile_covers/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('locataire', 'Locataire'), ('touriste', 'Touriste'), ('proprietaire', 'Propriétaire')], default='locataire', max_length=20),
        ),
    ]
