# Generated by Django 6.0.4 on 2026-07-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_photo_couverture_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activation_token',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='activation_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
