# Generated by Django 6.0.7 on 2026-07-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_activation_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_verification_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_verification_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
